#!/data/data/com.termux/files/usr/bin/sh
#
pkg upgrade -y -o Dpkg::Options::=--force-confnew 

mypacks="apt attr bash-completion bash binutils-bin binutils-libs \
         bzip2 ca-certificates command-not-found coreutils curl dash \
         debianutils dialog diffutils dos2unix dpkg ed file findutils \
         gawk gpgv grep gzip inetutils jq krb5 ldd ldns less libandroid-glob \
         libandroid-support libassuan libbz2 libc++ libcap-ng libcap libcrypt \
         libcurl libdb libedit libevent libexpat libgcrypt libgmp libgnutls \
         libgpg-error libiconv libidn2 liblz4 liblzma libmd libmpfr libnettle \
         libnghttp2 libnpth libpopt libresolv-wrapper libsmartcols libssh2 libtirpc \
         libunistring libuuid lsof man nano ncurses net-tools oniguruma \
         openssh-sftp-server openssh openssl-tool openssl patch pcre2 \
         pcre procps psmisc readline resolv-conf rsync runit sed tar \
         termux-am-socket termux-am termux-api termux-auth termux-exec \
         termux-keyring termux-licenses termux-services termux-tools tmux \
         tor torsocks tree unbound unzip util-linux vim-runtime vim wget \
         xxhash xz-utils zlib zsh-completions zsh zstd"

pkg install -y $(echo ${mypacks})

# define the xdg dirs
echo "# XDG Paths
export XDG_CONFIG_HOME="${HOME}/.config"
export XDG_CACHE_HOME="${HOME}/.cache"
export XDG_DATA_HOME="${HOME}/.local/share"

# zsh config dir
export ZDOTDIR="${XDG_CONFIG_HOME}/zsh"
" >> ${PREFIX}/etc/profile

source ${PREFIX}/etc/profile

mkdir -p {${XDG_DATA_HOME},${XDG_CACHE_HOME},${XDG_CONFIG_HOME}}
mkdir -p ${ZDOTDIR}

# TODO:
# 1. add your modifications to the ${PREFIX}/etc/tor/torrc file
# 2. start sshd, tor using sv ?  I need to remember how I was
#    adding those as services to termux-services
# 3. add your zsh related files to ~/.config/zsh
# 4. and I guess that's it after that??
